// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raftpb.proto

#ifndef PROTOBUF_raftpb_2eproto__INCLUDED
#define PROTOBUF_raftpb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace yaraft {
namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_raftpb_2eproto();
void protobuf_AssignDesc_raftpb_2eproto();
void protobuf_ShutdownFile_raftpb_2eproto();

class Entry;
class SnapshotMetadata;
class Snapshot;
class Message;
class HardState;
class ConfState;
class ConfChange;

enum EntryType {
  EntryNormal = 0,
  EntryConfChange = 1
};
bool EntryType_IsValid(int value);
const EntryType EntryType_MIN = EntryNormal;
const EntryType EntryType_MAX = EntryConfChange;
const int EntryType_ARRAYSIZE = EntryType_MAX + 1;

const ::google::protobuf::EnumDescriptor* EntryType_descriptor();
inline const ::std::string& EntryType_Name(EntryType value) {
  return ::google::protobuf::internal::NameOfEnum(
    EntryType_descriptor(), value);
}
inline bool EntryType_Parse(
    const ::std::string& name, EntryType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EntryType>(
    EntryType_descriptor(), name, value);
}
enum MessageType {
  MsgHup = 0,
  MsgBeat = 1,
  MsgProp = 2,
  MsgApp = 3,
  MsgAppResp = 4,
  MsgVote = 5,
  MsgVoteResp = 6,
  MsgSnap = 7,
  MsgHeartbeat = 8,
  MsgHeartbeatResp = 9,
  MsgUnreachable = 10,
  MsgSnapStatus = 11,
  MsgCheckQuorum = 12,
  MsgTransferLeader = 13,
  MsgTimeoutNow = 14,
  MsgReadIndex = 15,
  MsgReadIndexResp = 16,
  MsgPreVote = 17,
  MsgPreVoteResp = 18
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = MsgHup;
const MessageType MessageType_MAX = MsgPreVoteResp;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
enum ConfChangeType {
  ConfChangeAddNode = 0,
  ConfChangeRemoveNode = 1,
  ConfChangeUpdateNode = 2
};
bool ConfChangeType_IsValid(int value);
const ConfChangeType ConfChangeType_MIN = ConfChangeAddNode;
const ConfChangeType ConfChangeType_MAX = ConfChangeUpdateNode;
const int ConfChangeType_ARRAYSIZE = ConfChangeType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ConfChangeType_descriptor();
inline const ::std::string& ConfChangeType_Name(ConfChangeType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ConfChangeType_descriptor(), value);
}
inline bool ConfChangeType_Parse(
    const ::std::string& name, ConfChangeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConfChangeType>(
    ConfChangeType_descriptor(), name, value);
}
// ===================================================================

class Entry : public ::google::protobuf::Message {
 public:
  Entry();
  virtual ~Entry();

  Entry(const Entry& from);

  inline Entry& operator=(const Entry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Entry& default_instance();

  void Swap(Entry* other);

  // implements Message ----------------------------------------------

  Entry* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Entry& from);
  void MergeFrom(const Entry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 Term = 2;
  inline bool has_term() const;
  inline void clear_term();
  static const int kTermFieldNumber = 2;
  inline ::google::protobuf::uint64 term() const;
  inline void set_term(::google::protobuf::uint64 value);

  // optional uint64 Index = 3;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 3;
  inline ::google::protobuf::uint64 index() const;
  inline void set_index(::google::protobuf::uint64 value);

  // optional .yaraft.pb.EntryType Type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::yaraft::pb::EntryType type() const;
  inline void set_type(::yaraft::pb::EntryType value);

  // optional bytes Data = 4;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 4;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:yaraft.pb.Entry)
 private:
  inline void set_has_term();
  inline void clear_has_term();
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 index_;
  ::std::string* data_;
  int type_;
  friend void  protobuf_AddDesc_raftpb_2eproto();
  friend void protobuf_AssignDesc_raftpb_2eproto();
  friend void protobuf_ShutdownFile_raftpb_2eproto();

  void InitAsDefaultInstance();
  static Entry* default_instance_;
};
// -------------------------------------------------------------------

class SnapshotMetadata : public ::google::protobuf::Message {
 public:
  SnapshotMetadata();
  virtual ~SnapshotMetadata();

  SnapshotMetadata(const SnapshotMetadata& from);

  inline SnapshotMetadata& operator=(const SnapshotMetadata& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SnapshotMetadata& default_instance();

  void Swap(SnapshotMetadata* other);

  // implements Message ----------------------------------------------

  SnapshotMetadata* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SnapshotMetadata& from);
  void MergeFrom(const SnapshotMetadata& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .yaraft.pb.ConfState conf_state = 1;
  inline bool has_conf_state() const;
  inline void clear_conf_state();
  static const int kConfStateFieldNumber = 1;
  inline const ::yaraft::pb::ConfState& conf_state() const;
  inline ::yaraft::pb::ConfState* mutable_conf_state();
  inline ::yaraft::pb::ConfState* release_conf_state();
  inline void set_allocated_conf_state(::yaraft::pb::ConfState* conf_state);

  // optional uint64 index = 2;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 2;
  inline ::google::protobuf::uint64 index() const;
  inline void set_index(::google::protobuf::uint64 value);

  // optional uint64 term = 3;
  inline bool has_term() const;
  inline void clear_term();
  static const int kTermFieldNumber = 3;
  inline ::google::protobuf::uint64 term() const;
  inline void set_term(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:yaraft.pb.SnapshotMetadata)
 private:
  inline void set_has_conf_state();
  inline void clear_has_conf_state();
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_term();
  inline void clear_has_term();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::yaraft::pb::ConfState* conf_state_;
  ::google::protobuf::uint64 index_;
  ::google::protobuf::uint64 term_;
  friend void  protobuf_AddDesc_raftpb_2eproto();
  friend void protobuf_AssignDesc_raftpb_2eproto();
  friend void protobuf_ShutdownFile_raftpb_2eproto();

  void InitAsDefaultInstance();
  static SnapshotMetadata* default_instance_;
};
// -------------------------------------------------------------------

class Snapshot : public ::google::protobuf::Message {
 public:
  Snapshot();
  virtual ~Snapshot();

  Snapshot(const Snapshot& from);

  inline Snapshot& operator=(const Snapshot& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Snapshot& default_instance();

  void Swap(Snapshot* other);

  // implements Message ----------------------------------------------

  Snapshot* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Snapshot& from);
  void MergeFrom(const Snapshot& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // optional .yaraft.pb.SnapshotMetadata metadata = 2;
  inline bool has_metadata() const;
  inline void clear_metadata();
  static const int kMetadataFieldNumber = 2;
  inline const ::yaraft::pb::SnapshotMetadata& metadata() const;
  inline ::yaraft::pb::SnapshotMetadata* mutable_metadata();
  inline ::yaraft::pb::SnapshotMetadata* release_metadata();
  inline void set_allocated_metadata(::yaraft::pb::SnapshotMetadata* metadata);

  // @@protoc_insertion_point(class_scope:yaraft.pb.Snapshot)
 private:
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_metadata();
  inline void clear_has_metadata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* data_;
  ::yaraft::pb::SnapshotMetadata* metadata_;
  friend void  protobuf_AddDesc_raftpb_2eproto();
  friend void protobuf_AssignDesc_raftpb_2eproto();
  friend void protobuf_ShutdownFile_raftpb_2eproto();

  void InitAsDefaultInstance();
  static Snapshot* default_instance_;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  Message* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .yaraft.pb.MessageType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::yaraft::pb::MessageType type() const;
  inline void set_type(::yaraft::pb::MessageType value);

  // optional uint64 to = 2;
  inline bool has_to() const;
  inline void clear_to();
  static const int kToFieldNumber = 2;
  inline ::google::protobuf::uint64 to() const;
  inline void set_to(::google::protobuf::uint64 value);

  // optional uint64 from = 3;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 3;
  inline ::google::protobuf::uint64 from() const;
  inline void set_from(::google::protobuf::uint64 value);

  // optional uint64 term = 4;
  inline bool has_term() const;
  inline void clear_term();
  static const int kTermFieldNumber = 4;
  inline ::google::protobuf::uint64 term() const;
  inline void set_term(::google::protobuf::uint64 value);

  // optional uint64 logTerm = 5;
  inline bool has_logterm() const;
  inline void clear_logterm();
  static const int kLogTermFieldNumber = 5;
  inline ::google::protobuf::uint64 logterm() const;
  inline void set_logterm(::google::protobuf::uint64 value);

  // optional uint64 index = 6;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 6;
  inline ::google::protobuf::uint64 index() const;
  inline void set_index(::google::protobuf::uint64 value);

  // repeated .yaraft.pb.Entry entries = 7;
  inline int entries_size() const;
  inline void clear_entries();
  static const int kEntriesFieldNumber = 7;
  inline const ::yaraft::pb::Entry& entries(int index) const;
  inline ::yaraft::pb::Entry* mutable_entries(int index);
  inline ::yaraft::pb::Entry* add_entries();
  inline const ::google::protobuf::RepeatedPtrField< ::yaraft::pb::Entry >&
      entries() const;
  inline ::google::protobuf::RepeatedPtrField< ::yaraft::pb::Entry >*
      mutable_entries();

  // optional uint64 commit = 8;
  inline bool has_commit() const;
  inline void clear_commit();
  static const int kCommitFieldNumber = 8;
  inline ::google::protobuf::uint64 commit() const;
  inline void set_commit(::google::protobuf::uint64 value);

  // optional .yaraft.pb.Snapshot snapshot = 9;
  inline bool has_snapshot() const;
  inline void clear_snapshot();
  static const int kSnapshotFieldNumber = 9;
  inline const ::yaraft::pb::Snapshot& snapshot() const;
  inline ::yaraft::pb::Snapshot* mutable_snapshot();
  inline ::yaraft::pb::Snapshot* release_snapshot();
  inline void set_allocated_snapshot(::yaraft::pb::Snapshot* snapshot);

  // optional bool reject = 10;
  inline bool has_reject() const;
  inline void clear_reject();
  static const int kRejectFieldNumber = 10;
  inline bool reject() const;
  inline void set_reject(bool value);

  // optional uint64 rejectHint = 11;
  inline bool has_rejecthint() const;
  inline void clear_rejecthint();
  static const int kRejectHintFieldNumber = 11;
  inline ::google::protobuf::uint64 rejecthint() const;
  inline void set_rejecthint(::google::protobuf::uint64 value);

  // optional bytes context = 12;
  inline bool has_context() const;
  inline void clear_context();
  static const int kContextFieldNumber = 12;
  inline const ::std::string& context() const;
  inline void set_context(const ::std::string& value);
  inline void set_context(const char* value);
  inline void set_context(const void* value, size_t size);
  inline ::std::string* mutable_context();
  inline ::std::string* release_context();
  inline void set_allocated_context(::std::string* context);

  // @@protoc_insertion_point(class_scope:yaraft.pb.Message)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_to();
  inline void clear_has_to();
  inline void set_has_from();
  inline void clear_has_from();
  inline void set_has_term();
  inline void clear_has_term();
  inline void set_has_logterm();
  inline void clear_has_logterm();
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_commit();
  inline void clear_has_commit();
  inline void set_has_snapshot();
  inline void clear_has_snapshot();
  inline void set_has_reject();
  inline void clear_has_reject();
  inline void set_has_rejecthint();
  inline void clear_has_rejecthint();
  inline void set_has_context();
  inline void clear_has_context();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 to_;
  ::google::protobuf::uint64 from_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 logterm_;
  int type_;
  bool reject_;
  ::google::protobuf::uint64 index_;
  ::google::protobuf::RepeatedPtrField< ::yaraft::pb::Entry > entries_;
  ::google::protobuf::uint64 commit_;
  ::yaraft::pb::Snapshot* snapshot_;
  ::google::protobuf::uint64 rejecthint_;
  ::std::string* context_;
  friend void  protobuf_AddDesc_raftpb_2eproto();
  friend void protobuf_AssignDesc_raftpb_2eproto();
  friend void protobuf_ShutdownFile_raftpb_2eproto();

  void InitAsDefaultInstance();
  static Message* default_instance_;
};
// -------------------------------------------------------------------

class HardState : public ::google::protobuf::Message {
 public:
  HardState();
  virtual ~HardState();

  HardState(const HardState& from);

  inline HardState& operator=(const HardState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HardState& default_instance();

  void Swap(HardState* other);

  // implements Message ----------------------------------------------

  HardState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HardState& from);
  void MergeFrom(const HardState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 term = 1;
  inline bool has_term() const;
  inline void clear_term();
  static const int kTermFieldNumber = 1;
  inline ::google::protobuf::uint64 term() const;
  inline void set_term(::google::protobuf::uint64 value);

  // optional uint64 vote = 2;
  inline bool has_vote() const;
  inline void clear_vote();
  static const int kVoteFieldNumber = 2;
  inline ::google::protobuf::uint64 vote() const;
  inline void set_vote(::google::protobuf::uint64 value);

  // optional uint64 commit = 3;
  inline bool has_commit() const;
  inline void clear_commit();
  static const int kCommitFieldNumber = 3;
  inline ::google::protobuf::uint64 commit() const;
  inline void set_commit(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:yaraft.pb.HardState)
 private:
  inline void set_has_term();
  inline void clear_has_term();
  inline void set_has_vote();
  inline void clear_has_vote();
  inline void set_has_commit();
  inline void clear_has_commit();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 vote_;
  ::google::protobuf::uint64 commit_;
  friend void  protobuf_AddDesc_raftpb_2eproto();
  friend void protobuf_AssignDesc_raftpb_2eproto();
  friend void protobuf_ShutdownFile_raftpb_2eproto();

  void InitAsDefaultInstance();
  static HardState* default_instance_;
};
// -------------------------------------------------------------------

class ConfState : public ::google::protobuf::Message {
 public:
  ConfState();
  virtual ~ConfState();

  ConfState(const ConfState& from);

  inline ConfState& operator=(const ConfState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfState& default_instance();

  void Swap(ConfState* other);

  // implements Message ----------------------------------------------

  ConfState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConfState& from);
  void MergeFrom(const ConfState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 nodes = 1;
  inline int nodes_size() const;
  inline void clear_nodes();
  static const int kNodesFieldNumber = 1;
  inline ::google::protobuf::uint64 nodes(int index) const;
  inline void set_nodes(int index, ::google::protobuf::uint64 value);
  inline void add_nodes(::google::protobuf::uint64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      nodes() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_nodes();

  // @@protoc_insertion_point(class_scope:yaraft.pb.ConfState)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > nodes_;
  friend void  protobuf_AddDesc_raftpb_2eproto();
  friend void protobuf_AssignDesc_raftpb_2eproto();
  friend void protobuf_ShutdownFile_raftpb_2eproto();

  void InitAsDefaultInstance();
  static ConfState* default_instance_;
};
// -------------------------------------------------------------------

class ConfChange : public ::google::protobuf::Message {
 public:
  ConfChange();
  virtual ~ConfChange();

  ConfChange(const ConfChange& from);

  inline ConfChange& operator=(const ConfChange& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfChange& default_instance();

  void Swap(ConfChange* other);

  // implements Message ----------------------------------------------

  ConfChange* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConfChange& from);
  void MergeFrom(const ConfChange& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 ID = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIDFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // optional .yaraft.pb.ConfChangeType Type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::yaraft::pb::ConfChangeType type() const;
  inline void set_type(::yaraft::pb::ConfChangeType value);

  // optional uint64 NodeID = 3;
  inline bool has_nodeid() const;
  inline void clear_nodeid();
  static const int kNodeIDFieldNumber = 3;
  inline ::google::protobuf::uint64 nodeid() const;
  inline void set_nodeid(::google::protobuf::uint64 value);

  // optional bytes Context = 4;
  inline bool has_context() const;
  inline void clear_context();
  static const int kContextFieldNumber = 4;
  inline const ::std::string& context() const;
  inline void set_context(const ::std::string& value);
  inline void set_context(const char* value);
  inline void set_context(const void* value, size_t size);
  inline ::std::string* mutable_context();
  inline ::std::string* release_context();
  inline void set_allocated_context(::std::string* context);

  // @@protoc_insertion_point(class_scope:yaraft.pb.ConfChange)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_nodeid();
  inline void clear_has_nodeid();
  inline void set_has_context();
  inline void clear_has_context();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint64 nodeid_;
  ::std::string* context_;
  int type_;
  friend void  protobuf_AddDesc_raftpb_2eproto();
  friend void protobuf_AssignDesc_raftpb_2eproto();
  friend void protobuf_ShutdownFile_raftpb_2eproto();

  void InitAsDefaultInstance();
  static ConfChange* default_instance_;
};
// ===================================================================


// ===================================================================

// Entry

// optional uint64 Term = 2;
inline bool Entry::has_term() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Entry::set_has_term() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Entry::clear_has_term() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Entry::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
  clear_has_term();
}
inline ::google::protobuf::uint64 Entry::term() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Entry.Term)
  return term_;
}
inline void Entry::set_term(::google::protobuf::uint64 value) {
  set_has_term();
  term_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Entry.Term)
}

// optional uint64 Index = 3;
inline bool Entry::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Entry::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Entry::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Entry::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::uint64 Entry::index() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Entry.Index)
  return index_;
}
inline void Entry::set_index(::google::protobuf::uint64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Entry.Index)
}

// optional .yaraft.pb.EntryType Type = 1;
inline bool Entry::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Entry::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Entry::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Entry::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::yaraft::pb::EntryType Entry::type() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Entry.Type)
  return static_cast< ::yaraft::pb::EntryType >(type_);
}
inline void Entry::set_type(::yaraft::pb::EntryType value) {
  assert(::yaraft::pb::EntryType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Entry.Type)
}

// optional bytes Data = 4;
inline bool Entry::has_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Entry::set_has_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Entry::clear_has_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Entry::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& Entry::data() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Entry.Data)
  return *data_;
}
inline void Entry::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:yaraft.pb.Entry.Data)
}
inline void Entry::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:yaraft.pb.Entry.Data)
}
inline void Entry::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:yaraft.pb.Entry.Data)
}
inline ::std::string* Entry::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:yaraft.pb.Entry.Data)
  return data_;
}
inline ::std::string* Entry::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Entry::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:yaraft.pb.Entry.Data)
}

// -------------------------------------------------------------------

// SnapshotMetadata

// optional .yaraft.pb.ConfState conf_state = 1;
inline bool SnapshotMetadata::has_conf_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SnapshotMetadata::set_has_conf_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SnapshotMetadata::clear_has_conf_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SnapshotMetadata::clear_conf_state() {
  if (conf_state_ != NULL) conf_state_->::yaraft::pb::ConfState::Clear();
  clear_has_conf_state();
}
inline const ::yaraft::pb::ConfState& SnapshotMetadata::conf_state() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.SnapshotMetadata.conf_state)
  return conf_state_ != NULL ? *conf_state_ : *default_instance_->conf_state_;
}
inline ::yaraft::pb::ConfState* SnapshotMetadata::mutable_conf_state() {
  set_has_conf_state();
  if (conf_state_ == NULL) conf_state_ = new ::yaraft::pb::ConfState;
  // @@protoc_insertion_point(field_mutable:yaraft.pb.SnapshotMetadata.conf_state)
  return conf_state_;
}
inline ::yaraft::pb::ConfState* SnapshotMetadata::release_conf_state() {
  clear_has_conf_state();
  ::yaraft::pb::ConfState* temp = conf_state_;
  conf_state_ = NULL;
  return temp;
}
inline void SnapshotMetadata::set_allocated_conf_state(::yaraft::pb::ConfState* conf_state) {
  delete conf_state_;
  conf_state_ = conf_state;
  if (conf_state) {
    set_has_conf_state();
  } else {
    clear_has_conf_state();
  }
  // @@protoc_insertion_point(field_set_allocated:yaraft.pb.SnapshotMetadata.conf_state)
}

// optional uint64 index = 2;
inline bool SnapshotMetadata::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SnapshotMetadata::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SnapshotMetadata::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SnapshotMetadata::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::uint64 SnapshotMetadata::index() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.SnapshotMetadata.index)
  return index_;
}
inline void SnapshotMetadata::set_index(::google::protobuf::uint64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.SnapshotMetadata.index)
}

// optional uint64 term = 3;
inline bool SnapshotMetadata::has_term() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SnapshotMetadata::set_has_term() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SnapshotMetadata::clear_has_term() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SnapshotMetadata::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
  clear_has_term();
}
inline ::google::protobuf::uint64 SnapshotMetadata::term() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.SnapshotMetadata.term)
  return term_;
}
inline void SnapshotMetadata::set_term(::google::protobuf::uint64 value) {
  set_has_term();
  term_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.SnapshotMetadata.term)
}

// -------------------------------------------------------------------

// Snapshot

// optional bytes data = 1;
inline bool Snapshot::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Snapshot::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Snapshot::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Snapshot::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& Snapshot::data() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Snapshot.data)
  return *data_;
}
inline void Snapshot::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:yaraft.pb.Snapshot.data)
}
inline void Snapshot::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:yaraft.pb.Snapshot.data)
}
inline void Snapshot::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:yaraft.pb.Snapshot.data)
}
inline ::std::string* Snapshot::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:yaraft.pb.Snapshot.data)
  return data_;
}
inline ::std::string* Snapshot::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Snapshot::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:yaraft.pb.Snapshot.data)
}

// optional .yaraft.pb.SnapshotMetadata metadata = 2;
inline bool Snapshot::has_metadata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Snapshot::set_has_metadata() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Snapshot::clear_has_metadata() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Snapshot::clear_metadata() {
  if (metadata_ != NULL) metadata_->::yaraft::pb::SnapshotMetadata::Clear();
  clear_has_metadata();
}
inline const ::yaraft::pb::SnapshotMetadata& Snapshot::metadata() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Snapshot.metadata)
  return metadata_ != NULL ? *metadata_ : *default_instance_->metadata_;
}
inline ::yaraft::pb::SnapshotMetadata* Snapshot::mutable_metadata() {
  set_has_metadata();
  if (metadata_ == NULL) metadata_ = new ::yaraft::pb::SnapshotMetadata;
  // @@protoc_insertion_point(field_mutable:yaraft.pb.Snapshot.metadata)
  return metadata_;
}
inline ::yaraft::pb::SnapshotMetadata* Snapshot::release_metadata() {
  clear_has_metadata();
  ::yaraft::pb::SnapshotMetadata* temp = metadata_;
  metadata_ = NULL;
  return temp;
}
inline void Snapshot::set_allocated_metadata(::yaraft::pb::SnapshotMetadata* metadata) {
  delete metadata_;
  metadata_ = metadata;
  if (metadata) {
    set_has_metadata();
  } else {
    clear_has_metadata();
  }
  // @@protoc_insertion_point(field_set_allocated:yaraft.pb.Snapshot.metadata)
}

// -------------------------------------------------------------------

// Message

// optional .yaraft.pb.MessageType type = 1;
inline bool Message::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Message::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Message::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Message::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::yaraft::pb::MessageType Message::type() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.type)
  return static_cast< ::yaraft::pb::MessageType >(type_);
}
inline void Message::set_type(::yaraft::pb::MessageType value) {
  assert(::yaraft::pb::MessageType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.type)
}

// optional uint64 to = 2;
inline bool Message::has_to() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Message::set_has_to() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Message::clear_has_to() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Message::clear_to() {
  to_ = GOOGLE_ULONGLONG(0);
  clear_has_to();
}
inline ::google::protobuf::uint64 Message::to() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.to)
  return to_;
}
inline void Message::set_to(::google::protobuf::uint64 value) {
  set_has_to();
  to_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.to)
}

// optional uint64 from = 3;
inline bool Message::has_from() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Message::set_has_from() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Message::clear_has_from() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Message::clear_from() {
  from_ = GOOGLE_ULONGLONG(0);
  clear_has_from();
}
inline ::google::protobuf::uint64 Message::from() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.from)
  return from_;
}
inline void Message::set_from(::google::protobuf::uint64 value) {
  set_has_from();
  from_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.from)
}

// optional uint64 term = 4;
inline bool Message::has_term() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Message::set_has_term() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Message::clear_has_term() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Message::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
  clear_has_term();
}
inline ::google::protobuf::uint64 Message::term() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.term)
  return term_;
}
inline void Message::set_term(::google::protobuf::uint64 value) {
  set_has_term();
  term_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.term)
}

// optional uint64 logTerm = 5;
inline bool Message::has_logterm() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Message::set_has_logterm() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Message::clear_has_logterm() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Message::clear_logterm() {
  logterm_ = GOOGLE_ULONGLONG(0);
  clear_has_logterm();
}
inline ::google::protobuf::uint64 Message::logterm() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.logTerm)
  return logterm_;
}
inline void Message::set_logterm(::google::protobuf::uint64 value) {
  set_has_logterm();
  logterm_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.logTerm)
}

// optional uint64 index = 6;
inline bool Message::has_index() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Message::set_has_index() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Message::clear_has_index() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Message::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::uint64 Message::index() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.index)
  return index_;
}
inline void Message::set_index(::google::protobuf::uint64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.index)
}

// repeated .yaraft.pb.Entry entries = 7;
inline int Message::entries_size() const {
  return entries_.size();
}
inline void Message::clear_entries() {
  entries_.Clear();
}
inline const ::yaraft::pb::Entry& Message::entries(int index) const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.entries)
  return entries_.Get(index);
}
inline ::yaraft::pb::Entry* Message::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:yaraft.pb.Message.entries)
  return entries_.Mutable(index);
}
inline ::yaraft::pb::Entry* Message::add_entries() {
  // @@protoc_insertion_point(field_add:yaraft.pb.Message.entries)
  return entries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::yaraft::pb::Entry >&
Message::entries() const {
  // @@protoc_insertion_point(field_list:yaraft.pb.Message.entries)
  return entries_;
}
inline ::google::protobuf::RepeatedPtrField< ::yaraft::pb::Entry >*
Message::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:yaraft.pb.Message.entries)
  return &entries_;
}

// optional uint64 commit = 8;
inline bool Message::has_commit() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Message::set_has_commit() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Message::clear_has_commit() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Message::clear_commit() {
  commit_ = GOOGLE_ULONGLONG(0);
  clear_has_commit();
}
inline ::google::protobuf::uint64 Message::commit() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.commit)
  return commit_;
}
inline void Message::set_commit(::google::protobuf::uint64 value) {
  set_has_commit();
  commit_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.commit)
}

// optional .yaraft.pb.Snapshot snapshot = 9;
inline bool Message::has_snapshot() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Message::set_has_snapshot() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Message::clear_has_snapshot() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Message::clear_snapshot() {
  if (snapshot_ != NULL) snapshot_->::yaraft::pb::Snapshot::Clear();
  clear_has_snapshot();
}
inline const ::yaraft::pb::Snapshot& Message::snapshot() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.snapshot)
  return snapshot_ != NULL ? *snapshot_ : *default_instance_->snapshot_;
}
inline ::yaraft::pb::Snapshot* Message::mutable_snapshot() {
  set_has_snapshot();
  if (snapshot_ == NULL) snapshot_ = new ::yaraft::pb::Snapshot;
  // @@protoc_insertion_point(field_mutable:yaraft.pb.Message.snapshot)
  return snapshot_;
}
inline ::yaraft::pb::Snapshot* Message::release_snapshot() {
  clear_has_snapshot();
  ::yaraft::pb::Snapshot* temp = snapshot_;
  snapshot_ = NULL;
  return temp;
}
inline void Message::set_allocated_snapshot(::yaraft::pb::Snapshot* snapshot) {
  delete snapshot_;
  snapshot_ = snapshot;
  if (snapshot) {
    set_has_snapshot();
  } else {
    clear_has_snapshot();
  }
  // @@protoc_insertion_point(field_set_allocated:yaraft.pb.Message.snapshot)
}

// optional bool reject = 10;
inline bool Message::has_reject() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Message::set_has_reject() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Message::clear_has_reject() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Message::clear_reject() {
  reject_ = false;
  clear_has_reject();
}
inline bool Message::reject() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.reject)
  return reject_;
}
inline void Message::set_reject(bool value) {
  set_has_reject();
  reject_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.reject)
}

// optional uint64 rejectHint = 11;
inline bool Message::has_rejecthint() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Message::set_has_rejecthint() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Message::clear_has_rejecthint() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Message::clear_rejecthint() {
  rejecthint_ = GOOGLE_ULONGLONG(0);
  clear_has_rejecthint();
}
inline ::google::protobuf::uint64 Message::rejecthint() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.rejectHint)
  return rejecthint_;
}
inline void Message::set_rejecthint(::google::protobuf::uint64 value) {
  set_has_rejecthint();
  rejecthint_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.rejectHint)
}

// optional bytes context = 12;
inline bool Message::has_context() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Message::set_has_context() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Message::clear_has_context() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Message::clear_context() {
  if (context_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_->clear();
  }
  clear_has_context();
}
inline const ::std::string& Message::context() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.Message.context)
  return *context_;
}
inline void Message::set_context(const ::std::string& value) {
  set_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_ = new ::std::string;
  }
  context_->assign(value);
  // @@protoc_insertion_point(field_set:yaraft.pb.Message.context)
}
inline void Message::set_context(const char* value) {
  set_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_ = new ::std::string;
  }
  context_->assign(value);
  // @@protoc_insertion_point(field_set_char:yaraft.pb.Message.context)
}
inline void Message::set_context(const void* value, size_t size) {
  set_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_ = new ::std::string;
  }
  context_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:yaraft.pb.Message.context)
}
inline ::std::string* Message::mutable_context() {
  set_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:yaraft.pb.Message.context)
  return context_;
}
inline ::std::string* Message::release_context() {
  clear_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = context_;
    context_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Message::set_allocated_context(::std::string* context) {
  if (context_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete context_;
  }
  if (context) {
    set_has_context();
    context_ = context;
  } else {
    clear_has_context();
    context_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:yaraft.pb.Message.context)
}

// -------------------------------------------------------------------

// HardState

// optional uint64 term = 1;
inline bool HardState::has_term() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HardState::set_has_term() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HardState::clear_has_term() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HardState::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
  clear_has_term();
}
inline ::google::protobuf::uint64 HardState::term() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.HardState.term)
  return term_;
}
inline void HardState::set_term(::google::protobuf::uint64 value) {
  set_has_term();
  term_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.HardState.term)
}

// optional uint64 vote = 2;
inline bool HardState::has_vote() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HardState::set_has_vote() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HardState::clear_has_vote() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HardState::clear_vote() {
  vote_ = GOOGLE_ULONGLONG(0);
  clear_has_vote();
}
inline ::google::protobuf::uint64 HardState::vote() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.HardState.vote)
  return vote_;
}
inline void HardState::set_vote(::google::protobuf::uint64 value) {
  set_has_vote();
  vote_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.HardState.vote)
}

// optional uint64 commit = 3;
inline bool HardState::has_commit() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HardState::set_has_commit() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HardState::clear_has_commit() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HardState::clear_commit() {
  commit_ = GOOGLE_ULONGLONG(0);
  clear_has_commit();
}
inline ::google::protobuf::uint64 HardState::commit() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.HardState.commit)
  return commit_;
}
inline void HardState::set_commit(::google::protobuf::uint64 value) {
  set_has_commit();
  commit_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.HardState.commit)
}

// -------------------------------------------------------------------

// ConfState

// repeated uint64 nodes = 1;
inline int ConfState::nodes_size() const {
  return nodes_.size();
}
inline void ConfState::clear_nodes() {
  nodes_.Clear();
}
inline ::google::protobuf::uint64 ConfState::nodes(int index) const {
  // @@protoc_insertion_point(field_get:yaraft.pb.ConfState.nodes)
  return nodes_.Get(index);
}
inline void ConfState::set_nodes(int index, ::google::protobuf::uint64 value) {
  nodes_.Set(index, value);
  // @@protoc_insertion_point(field_set:yaraft.pb.ConfState.nodes)
}
inline void ConfState::add_nodes(::google::protobuf::uint64 value) {
  nodes_.Add(value);
  // @@protoc_insertion_point(field_add:yaraft.pb.ConfState.nodes)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ConfState::nodes() const {
  // @@protoc_insertion_point(field_list:yaraft.pb.ConfState.nodes)
  return nodes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ConfState::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:yaraft.pb.ConfState.nodes)
  return &nodes_;
}

// -------------------------------------------------------------------

// ConfChange

// optional uint64 ID = 1;
inline bool ConfChange::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConfChange::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConfChange::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConfChange::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 ConfChange::id() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.ConfChange.ID)
  return id_;
}
inline void ConfChange::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.ConfChange.ID)
}

// optional .yaraft.pb.ConfChangeType Type = 2;
inline bool ConfChange::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConfChange::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConfChange::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConfChange::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::yaraft::pb::ConfChangeType ConfChange::type() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.ConfChange.Type)
  return static_cast< ::yaraft::pb::ConfChangeType >(type_);
}
inline void ConfChange::set_type(::yaraft::pb::ConfChangeType value) {
  assert(::yaraft::pb::ConfChangeType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.ConfChange.Type)
}

// optional uint64 NodeID = 3;
inline bool ConfChange::has_nodeid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ConfChange::set_has_nodeid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ConfChange::clear_has_nodeid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ConfChange::clear_nodeid() {
  nodeid_ = GOOGLE_ULONGLONG(0);
  clear_has_nodeid();
}
inline ::google::protobuf::uint64 ConfChange::nodeid() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.ConfChange.NodeID)
  return nodeid_;
}
inline void ConfChange::set_nodeid(::google::protobuf::uint64 value) {
  set_has_nodeid();
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:yaraft.pb.ConfChange.NodeID)
}

// optional bytes Context = 4;
inline bool ConfChange::has_context() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ConfChange::set_has_context() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ConfChange::clear_has_context() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ConfChange::clear_context() {
  if (context_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_->clear();
  }
  clear_has_context();
}
inline const ::std::string& ConfChange::context() const {
  // @@protoc_insertion_point(field_get:yaraft.pb.ConfChange.Context)
  return *context_;
}
inline void ConfChange::set_context(const ::std::string& value) {
  set_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_ = new ::std::string;
  }
  context_->assign(value);
  // @@protoc_insertion_point(field_set:yaraft.pb.ConfChange.Context)
}
inline void ConfChange::set_context(const char* value) {
  set_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_ = new ::std::string;
  }
  context_->assign(value);
  // @@protoc_insertion_point(field_set_char:yaraft.pb.ConfChange.Context)
}
inline void ConfChange::set_context(const void* value, size_t size) {
  set_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_ = new ::std::string;
  }
  context_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:yaraft.pb.ConfChange.Context)
}
inline ::std::string* ConfChange::mutable_context() {
  set_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    context_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:yaraft.pb.ConfChange.Context)
  return context_;
}
inline ::std::string* ConfChange::release_context() {
  clear_has_context();
  if (context_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = context_;
    context_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ConfChange::set_allocated_context(::std::string* context) {
  if (context_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete context_;
  }
  if (context) {
    set_has_context();
    context_ = context;
  } else {
    clear_has_context();
    context_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:yaraft.pb.ConfChange.Context)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace yaraft

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::yaraft::pb::EntryType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yaraft::pb::EntryType>() {
  return ::yaraft::pb::EntryType_descriptor();
}
template <> struct is_proto_enum< ::yaraft::pb::MessageType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yaraft::pb::MessageType>() {
  return ::yaraft::pb::MessageType_descriptor();
}
template <> struct is_proto_enum< ::yaraft::pb::ConfChangeType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yaraft::pb::ConfChangeType>() {
  return ::yaraft::pb::ConfChangeType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_raftpb_2eproto__INCLUDED
